Repository netlify/netlify-redirect-parser, pull requests merged in 2021-06, with the labels that each got.

#197 feat: improve `README.md`
  README.md
Labels: type: chore, type: feature

#189 chore!: default `params` to an empty object
  src/common.js
  src/line-parser.js
  src/line-parser.test.js
  src/netlify-config-parser.js
  src/netlify-config-parser.test.js
Labels: type: chore

#186 chore: small performance improvement
  src/common.js
  src/line-parser.js
  src/netlify-config-parser.js
Labels: type: chore

#190 chore: fix imports and exports
  src/index.js
  src/line-parser.js
  src/line-parser.test.js
  src/netlify-config-parser.js
  src/netlify-config-parser.test.js
Labels: type: chore

#193 Fixes linting
  .eslintrc.js
  package.json
  src/line-parser.js
Labels: type: bug, type: chore

#192 chore: simplify URL-related logic
  src/common.js
  src/line-parser.js
Labels: type: chore

#187 chore: remove duplicated logic
  src/line-parser.js
  src/netlify-config-parser.js
Labels: type: chore

#185 chore: simplify comment trimming logic
  src/line-parser.js
Labels: type: chore

#194 chore!: rename `params` to `query`
  src/line-parser.js
  src/line-parser.test.js
  src/netlify-config-parser.js
  src/netlify-config-parser.test.js
Labels: type: chore

#184 feat!: ensure `headers` is always set
  src/line-parser.js
  src/line-parser.test.js
  src/netlify-config-parser.js
  src/netlify-config-parser.test.js
Labels: type: chore, type: feature

#191 feat: improve error handling
  src/common.js
  src/line-parser.js
  src/netlify-config-parser.js
Labels: type: feature

#195 fix!: `signed` backward compatibility priority
  src/netlify-config-parser.js
Labels: type: bug, type: chore

#196 feat: add support for parsing Edge handlers location
  src/line-parser.js
  src/line-parser.test.js
  src/netlify-config-parser.js
  src/netlify-config-parser.test.js
Labels: type: feature

#198 feat!: use exceptions
  src/common.js
  src/line-parser.js
  src/line-parser.test.js
  src/netlify-config-parser.js
  src/netlify-config-parser.test.js
Labels: type: feature

#199 chore: fix `func-style` linting rule
  .eslintrc.js
  src/common.js
  src/line-parser.js
  src/netlify-config-parser.js
Labels: type: chore

#200 chore: re-order lines
  src/common.js
  src/line-parser.js
  src/netlify-config-parser.js
Labels: type: chore

#201 chore: remove duplicate code
  src/common.js
  src/line-parser.js
  src/netlify-config-parser.js
Labels: type: chore

#205 fix: allow non-force forward rules
  src/netlify-config-parser.js
Labels: type: bug

#204 chore: remove duplicated code in tests
  tests/line-parser.js
  tests/netlify-config-parser.js
Labels: type: chore

#202 chore: remove duplicate code
  src/common.js
  src/line-parser.js
  src/netlify-config-parser.js
Labels: type: chore

#206 chore: make tests more uniform
  tests/fixtures/absolute_country_redirects
  tests/line-parser.js
Labels: type: chore

#207 chore: use data-driven testing
  package-lock.json
  package.json
  tests/helpers/main.js
  tests/line-parser.js
  tests/netlify-config-parser.js
Labels: type: chore

#210 fix: validation of `from`
  src/common.js
  src/line-parser.js
  src/netlify-config-parser.js
  tests/line-parser.js
Labels: type: bug, type: chore

#209 chore: move a few lines
  src/common.js
Labels: type: chore

#211 chore: remove duplicated code
  src/common.js
  src/line-parser.js
  src/netlify-config-parser.js
Labels: type: chore

#208 chore: refactor forward rules
  src/line-parser.js
  src/netlify-config-parser.js
Labels: type: chore

#220 feat: validate that `redirects` is an array
  src/netlify-config-parser.js
Labels: type: feature

#223 chore: remove Edge handlers parsing
  src/line-parser.js
  src/netlify-config-parser.js
  tests/helpers/main.js
Labels: type: chore

#217 chore: renames some variables
  src/line-parser.js
  src/netlify-config-parser.js
Labels: type: chore

#219 chore: simplify status parsing
  src/line-parser.js
Labels: type: chore

#216 chore: remove duplicate code
  src/line-parser.js
Labels: type: chore

#213 chore: rename variables
  src/line-parser.js
Labels: type: chore

#214 chore: simplify code
  src/line-parser.js
Labels: type: chore

#212 chore: refactor forward rules
  src/common.js
  src/line-parser.js
  src/netlify-config-parser.js
Labels: type: chore

#215 chore: reorder fields
  src/line-parser.js
  src/netlify-config-parser.js
Labels: type: chore

#218 chore: add comments
  src/common.js
  src/line-parser.js
  src/netlify-config-parser.js
Labels: type: chore

#224 chore: fix filename case
  .eslintrc.js
  src/index.js
  src/line_parser.js
  src/netlify_config_parser.js
  tests/line_parser.js
  tests/netlify_config_parser.js
Labels: type: chore

#228 chore: add `LICENSE` file
  LICENSE
Labels: type: chore

#227 chore: add `.editorconfig`
  .editorconfig
Labels: type: chore

#225 chore: improve linting
  .eslintrc.js
  tests/line_parser.js
Labels: type: chore

#226 chore: add test coverage
  README.md
  codecov.yml
Labels: type: chore

#235 chore(deps): add allowed versions for renovate
  renovate.json5
Labels: type: chore

#248 feat: allow `_redirects` to be optional
  package-lock.json
  package.json
  src/line_parser.js
  tests/line_parser.js
Labels: type: feature

#247 feat: do not use `@netlify/config`
  package-lock.json
  package.json
  src/netlify_config_parser.js
  tests/fixtures/netlify_config/invalid_toml.toml
  tests/netlify_config_parser.js
Labels: type: feature

#249 feat: add logic to merge redirects
  src/index.js
  src/merge.js
  tests/merge.js
Labels: type: feature

#246 fix: separate normalization logic
  src/common.js
  src/line_parser.js
  src/netlify_config_parser.js
  src/url.js
  tests/line_parser.js
Labels: type: chore

#253 feat!: change the main exported steps
  src/index.js
  src/line_parser.js
  src/netlify_config_parser.js
  src/normalize.js
  tests/line_parser.js
  tests/netlify_config_parser.js
Labels: type: feature

#254 feat: add `parseAllRedirects()`
  src/all.js
  src/index.js
  src/line_parser.js
  src/netlify_config_parser.js
  tests/all.js
Labels: type: feature

#258 chore: add 100% test coverage
  tests/fixtures/redirects_file/invalid_no_to_query
  tests/line_parser.js
Labels: type: chore

#259 feat: improve redirects merging
  src/merge.js
  tests/merge.js
Labels: type: feature

#261 chore: add more tests
  tests/fixtures/netlify_config/from_no_slash.toml
  tests/fixtures/redirects_file/invalid_no_slash
  tests/line_parser.js
  tests/netlify_config_parser.js
Labels: type: chore

#262 feat: improve error message
  src/line_parser.js
  tests/line_parser.js
Labels: type: feature

#272 fix: add `origin` field
  src/normalize.js
  tests/all.js
  tests/line_parser.js
  tests/merge.js
  tests/netlify_config_parser.js
Labels: type: bug

#274 fix!: rename `to` field to `destination`
  src/normalize.js
  tests/all.js
  tests/line_parser.js
  tests/merge.js
  tests/netlify_config_parser.js
Labels: type: bug

#275 fix!: rename `query` to `parameters`
  src/normalize.js
  tests/all.js
  tests/helpers/main.js
  tests/line_parser.js
  tests/netlify_config_parser.js
Labels: type: bug

#276 fix!: fix conditions parsing
  src/conditions.js
  src/normalize.js
  tests/fixtures/netlify_config/conditions_country_case.toml
  tests/fixtures/netlify_config/conditions_language_case.toml
  tests/fixtures/netlify_config/conditions_role_case.toml
  tests/fixtures/redirects_file/conditions_country_case
  tests/fixtures/redirects_file/conditions_language_case
  tests/fixtures/redirects_file/conditions_role_case
  tests/line_parser.js
  tests/netlify_config_parser.js
Labels: type: bug

#280 feat!: fix return value shape
  src/normalize.js
  tests/all.js
  tests/helpers/main.js
  tests/line_parser.js
  tests/merge.js
  tests/netlify_config_parser.js
Labels: type: feature

#286 chore(deps): ignore test-each updates for versions >=3
  renovate.json5
Labels: type: chore
