Repository netlify/netlify-redirect-parser, pull requests merged in 2021-08, with the labels that each got.

#300 chore: add kodiak
  .github/.kodiak.toml
Labels: type: chore

#301 feat: add `minimal` option
  src/all.js
  src/normalize.js
  tests/all.js
  tests/fixtures/netlify_config/minimal.toml
  tests/helpers/main.js
  tests/netlify_config_parser.js
Labels: type: feature

#302 chore: fix release process
  .github/workflows/release-please.yml
Labels: type: chore

#309 chore!: drop support for Node 8
  .github/workflows/workflow.yml
  package.json
  renovate.json5
Labels: type: chore

#310 chore: small refactoring
  src/line_parser.js
Labels: type: chore

#312 feat: remove duplicates
  src/merge.js
  tests/merge.js
Labels: type: feature

#314 feat!: add lenient parsing
  src/all.js
  src/line_parser.js
  src/merge.js
  src/netlify_config_parser.js
  src/normalize.js
  src/results.js
  tests/all.js
  tests/line_parser.js
  tests/merge.js
  tests/netlify_config_parser.js
Labels: type: feature

#316 feat: add `configRedirects` argument to `parseAllRedirects()`
  src/all.js
  tests/all.js
Labels: type: feature

#318 feat!: simplify exported methods
  src/all.js
  src/index.js
  src/merge.js
  src/normalize.js
  tests/all.js
  tests/line_parser.js
  tests/merge.js
  tests/netlify_config_parser.js
Labels: type: feature

#320 chore: simplify tests
  tests/all.js
  tests/fixtures/redirects_file/simple
  tests/fixtures/redirects_file/simple_multiple
  tests/helpers/main.js
  tests/line_parser.js
  tests/merge.js
  tests/netlify_config_parser.js
Labels: type: chore

#326 chore: add `path-exists` to `renovate.json5`
  renovate.json5
Labels: type: chore

#327 fix: handle `_redirects` with wrong file type
  src/line_parser.js
  tests/fixtures/redirects_file/invalid_dir/.gitkeep
  tests/line_parser.js
Labels: type: bug

#329 bug: patch fossa install process
  .github/workflows/fossa.yml
Labels: type: chore

#338 chore(ci): cache npm cache dir between workflow execs
  .github/workflows/release-please.yml
  .github/workflows/workflow.yml
Labels: type: chore, automerge
